### ISSUE TITLE
Doesn't override env var if it exists

### ISSUE THREAD

**Issue by maruks** [tpope/lein-dotenv#2]
Your plugin doesn't override env var if it exists

```
(if (m k (System/getenv k))
        m
```

**Comment by tpope** [comment]
This was intentional, and matches how other dotenv libraries (e.g., [the Ruby library](https://github.com/bkeepers/dotenv)) work. The idea is that `.env` provides defaults, and you can temporarily override the defaults by setting an environment variable.
